title: Fikri Anuar # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi my name is Fikri.
  <br><br>
  I'm a software engineer.
  <br><br>
  <a href="https://www.linkedin.com/in/fikrianuar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-3848D4JC4J # your Google Analytics tracking ID here
